In [1]:
import statsmodels.api as sm
import statsmodels.formula.api as smf
from sklearn import preprocessing
import sklearn.model_selection as ms
import sklearn.metrics as sklm
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import numpy.random as nr
import seaborn as sns
from datetime import date
from sklearn import linear_model
from sklearn.preprocessing import StandardScaler, RobustScaler
from sklearn.linear_model import Lasso, LassoCV
import scipy.stats as ss
from scipy.stats import skew
import math
from scipy.stats import norm
import warnings
warnings.filterwarnings('ignore')

In [2]:
TrainData = pd.read_csv('train.csv')
TestData=pd.read_csv('test.csv')

In [3]:
for col in ('ExterQual','HeatingQC','FireplaceQu','GarageQual','KitchenQual','BsmtQual','BsmtCond','GarageCond','PoolQC'):
    TrainData[col]=TrainData[col].fillna(0)
    TestData[col]=TestData[col].fillna(0)
    TrainData[col][TrainData[col] == 'Ex'] = 9
    TrainData[col][TrainData[col] == 'Gd'] = 7
    TrainData[col][TrainData[col] == 'TA'] = 5
    TrainData[col][TrainData[col] == 'Fa'] = 3
    TrainData[col][TrainData[col] == 'Po'] = 1
    TrainData[col][TrainData[col] == 'NA'] = 0
    TestData[col][TestData[col] == 'Ex'] = 9
    TestData[col][TestData[col] == 'Gd'] = 7
    TestData[col][TestData[col] == 'TA'] = 5
    TestData[col][TestData[col] == 'Fa'] = 3
    TestData[col][TestData[col] == 'Po'] = 1
    TestData[col][TestData[col] == 'NA'] = 0
    TestData[col].astype('int64')
    TrainData[col].astype('int64')

In [4]:
TrainData.head(5)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
#I want to try to understand the random forest regressor 
#-- features and leaf samples, BEFORE i run this.
# I have 24 Features Chosen

# We adjust with n_estimators and max_features
# max_features=n_features is good for regression problems
#Train = pd.DataFrame(TrainData[['SalePrice','TotRmsAbvGrd','GrLivArea','OverallQual','BldgType','EnclosedPorch','Fireplaces','GarageCars','HouseStyle','LotFrontage','MasVnrType','MiscFeature','MoSold','MSZoning','Neighborhood','OpenPorchSF','PavedDrive','PoolArea','RoofMatl','ScreenPorch','Street','Utilities','WoodDeckSF','YearRemodAdd','YrSold']])
#Test = pd.DataFrame(TestData[['TotRmsAbvGrd','GrLivArea','OverallQual','BldgType','EnclosedPorch','Fireplaces','GarageCars','HouseStyle','LotFrontage','MasVnrType','MiscFeature','MoSold','MSZoning','Neighborhood','OpenPorchSF','PavedDrive','PoolArea','RoofMatl','ScreenPorch','Street','Utilities','WoodDeckSF','YearRemodAdd','YrSold']])
TrainTarget = TrainData[['SalePrice']]
TrainCol = TrainData[['TotRmsAbvGrd','1stFlrSF','OverallQual','FullBath','LotFrontage','YearRemodAdd','YearBuilt','ExterQual','GrLivArea']]
TestCol = TestData[['TotRmsAbvGrd','1stFlrSF','OverallQual','FullBath','LotFrontage','YearRemodAdd','YearBuilt','ExterQual','GrLivArea']]
#A hack initially set up for for OneHotEncoder. Complete coverage of categories for dummy variables
TrainTest = TrainCol.append(TestCol)

In [6]:
TrainTestCol = pd.get_dummies(TrainTest,dummy_na=True)
#TrainTestCol.drop('ExterQual_nan',axis=0)

In [7]:
#TrainTest['MiscFeature']=TrainTest['MiscFeature'].fillna('None')
#TrainTest['MasVnrType']=TrainTest['MasVnrType'].fillna('None')
TrainTestCol['LotFrontage']=TrainTestCol['LotFrontage'].fillna(0)
#TrainTest['GarageCars']=TrainTest['GarageCars'].fillna(0)
#TrainTest['MSZoning']=TrainTest['MSZoning'].fillna('None')
TrainTestCol.to_csv('TrainTestCheck.csv')

Train = TrainTestCol.iloc[:1460]
Test = TrainTestCol.iloc[1460:]


Train.drop('ExterQual_nan',axis=1)
Test.drop('ExterQual_nan',axis=1)

,TotRmsAbvGrd,1stFlrSF,OverallQual,FullBath,LotFrontage,YearRemodAdd,YearBuilt,GrLivArea,ExterQual_3.0,ExterQual_5.0,ExterQual_7.0,ExterQual_9.0
0,5,896,5,1,80.0,1961,1961,896,0,1,0,0
1,6,1329,6,1,81.0,1958,1958,1329,0,1,0,0
2,6,928,5,2,74.0,1998,1997,1629,0,1,0,0
3,7,926,6,2,78.0,1998,1998,1604,0,1,0,0
4,5,1280,8,2,43.0,1992,1992,1280,0,0,1,0
5,7,763,6,2,75.0,1994,1993,1655,0,1,0,0
6,6,1187,6,2,0.0,2007,1992,1187,0,1,0,0
7,7,789,6,2,63.0,1998,1998,1465,0,1,0,0
8,5,1341,7,1,85.0,1990,1990,1341,0,1,0,0
9,4,882,4,1,70.0,1970,1970,882,0,1,0,0
10,5,1337,7,2,26.0,1999,1999,1337,0,0,1,0
11,5,483,6,1,21.0,1971,1971,987,0,1,0,0
12,6,525,5,1,21.0,1971,1971,1092,0,1,0,0
13,6,855,6,2,24.0,1975,1975,1456,0,1,0,0
14,4,836,7,1,24.0,1975,1975,836,0,1,0,0
15,10,1627,9,2,102.0,2010,2009,2334,0,0,0,1
16,7,1544,8,2,94.0,2010,2009,1544,0,0,1,0
17,7,1698,9,2,90.0,2005,2005,1698,0,0,1,0
18,8,1822,8,2,79.0,2006,2005,1822,0,0,1,0
19,10,2696,9,2,110.0,2004,2003,2696,0,0,0,1
20,7,1687,8,2,105.0,2002,2002,2250,0,0,1,0
21,6,1370,8,2,41.0,2006,2006,1370,0,0,1,0
22,6,1324,6,2,100.0,2005,2005,1324,0,0,1,0
23,6,1145,7,2,43.0,2006,2006,1145,0,0,1,0
24,7,744,7,2,67.0,2004,2004,1374,0,0,1,0
25,7,847,7,2,63.0,2004,2004,1733,0,0,1,0
26,7,1645,8,2,60.0,1998,1998,2475,0,0,1,0
27,6,1595,8,2,73.0,2006,2005,1595,0,0,1,0
28,4,1218,7,2,92.0,2010,2009,1218,0,0,1,0
29,6,1468,6,2,84.0,2005,2005,1468,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1429,4,641,4,1,50.0,1950,1925,641,0,1,0,0
1430,6,967,6,2,75.0,1957,1957,1638,0,1,0,0
1431,5,729,3,1,69.0,1950,1945,729,0,1,0,0
1432,8,1060,5,2,50.0,1951,1951,1396,1,0,0,0
1433,6,576,3,1,60.0,1950,1916,936,0,1,0,0
1434,5,1778,8,2,41.0,2006,2005,1778,0,0,1,0
1435,5,1646,8,2,44.0,2005,2004,1646,0,0,1,0
1436,6,1625,6,2,69.0,1979,1979,1625,0,1,0,0
1437,10,1664,6,2,65.0,1978,1978,1664,0,1,0,0
1438,7,1491,8,2,70.0,2001,2001,1491,0,0,1,0
1439,6,1210,6,2,140.0,1975,1975,1210,0,1,0,0
1440,6,1650,6,1,0.0,1958,1958,1650,0,1,0,0
1441,5,1403,6,2,0.0,2000,2000,1403,0,0,1,0
1442,8,1960,8,2,95.0,2006,2005,1960,0,0,1,0
1443,9,1838,9,2,88.0,2006,2005,1838,0,0,0,1
1444,6,1600,1,1,125.0,1951,1951,1600,0,1,0,0
1445,8,1368,7,2,78.0,1997,1997,1368,0,1,0,0
1446,5,616,5,1,41.0,1977,1977,1304,0,1,0,0
1447,5,874,5,1,58.0,2003,1968,874,0,1,0,0
1448,8,1652,5,2,0.0,1970,1970,1652,0,1,0,0
1449,3,630,4,1,21.0,1970,1970,630,0,1,0,0
1450,5,546,4,1,21.0,1972,1972,1092,0,1,0,0
1451,8,1360,5,1,80.0,1979,1969,1360,0,1,0,0
1452,5,546,4,1,21.0,1970,1970,1092,0,1,0,0
1453,5,546,4,1,21.0,1970,1970,1092,0,1,0,0
1454,5,546,4,1,21.0,1970,1970,1092,0,1,0,0
1455,6,546,4,1,21.0,1970,1970,1092,0,1,0,0
1456,7,1224,5,1,160.0,1996,1960,1224,0,1,0,0
1457,6,970,5,1,62.0,1992,1992,970,0,1,0,0
1458,9,996,7,2,74.0,1994,1993,2000,0,1,0,0

In [8]:
sc=RobustScaler()
TrainTestCol=sc.fit_transform(TrainTestCol)

In [9]:
Train.to_csv('Traincheck.csv')
Test.to_csv('TestCheck.csv')
y=TrainTarget
#Train=Train.drop('SalePrice', axis=1)
#Test=Test.drop('SalePrice', axis=1)

In [10]:
y=np.log(y)
#Test = Test.iloc[:,1:]

In [11]:
#Setting Up a Poisson Regression Model -- statsmodels.genmod.families.family.Poisson
#Concept - dataset is right skewed. A regression that models a right-skewed distribution is worth investigating.
#PoiReg = sm.GLM(y,Train,data=Train, family=sm.families.Poisson()).fit()
LassoReg = Lasso(alpha =0.001, random_state=1).fit(Train,y)

NameError: name 'Lasso' is not defined

In [ ]:
Test.iloc[:,1:].head(5)

In [ ]:
Train.iloc[:,1:].head(5)

In [ ]:
#print PoiReg.summary()
Result = pd.DataFrame(LassoReg.predict(Test))
Result = np.exp(Result)

In [ ]:
Result.to_csv('resultreg9.csv')
#Output = pd.DataFrame({'Id':TestData[['Id']], 'SalePrice':Result})
#Output.to_csv('submissiontmb.csv', index=False)